name: CI - Unit tests
run-name: Pull request - ${{ github.event.pull_request.title }}
on: 
  pull_request:
    branches: 
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
        
      - name: Install dependencies
        run: npm install
      
      - name: Run unit tests
        run: npm test

      - name: Run e2e tests
        run: npm run test:e2e
